context:
  version: "0.14.0"
  python_min: '3.12'

package:
  name: bhklab-project-template
  version: ${{ version }}

# if you want to find the sha:
# curl -sL https://pypi.org/packages/source/b/bhklab-project-template/bhklab_project_template-0.13.0.tar.gz | shasum -a 256

source:
  url: https://pypi.org/packages/source/b/bhklab-project-template/bhklab_project_template-${{ version }}.tar.gz
  sha256: 51e9b0d716961aa6f957630a591517fecfd9f5341c74530b4e0ce0f3bc33cfee

build:
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - bhklab-project-template = bhklab_project_template.__init__:cli
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - click <9,>=8.2.0
    - copier <10,>=9.7.1
    - "rich-click "
    - rich <15,>=14.0.0
    - loguru <1,>=0.7.0
    - platformdirs <5,>=4.3.8

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - bhklab_project_template
      pip_check: true

about:
  summary: A simple CLI tool to create new BHKLab projects from a template
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/bhklab/bhklab-project-template
extra:
  recipe-maintainers:
    - jjjermiah
    - mattbocc
    - strixy16
